FROM golang:1.16

ENV XDG_CACHE_HOME=/tmp/.cache

RUN \
  curl -sS -L -o kubebuilder.tar.gz https://github.com/kubernetes-sigs/kubebuilder/releases/download/v2.3.1/kubebuilder_2.3.1_linux_amd64.tar.gz && \
  tar xvf kubebuilder.tar.gz && \
  mv kubebuilder_2.3.1_linux_amd64 /usr/local/kubebuilder && \
  chmod +x /usr/local/kubebuilder/bin/* 
