name: Renovate

on:
  schedule:
    - cron: "0/20 0-6 * * 0,6"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          private_key: ${{ secrets.RENOVATE_APP_PEM }}

      - name: Checkout
        uses: actions/checkout@v7

      - name: Update dependencies
        uses: renovatebot/github-action@8217b3fc286df088d7c27f3255fe8414463bc0fd # v46.1.15
        with:
          configurationFile: .github/renovate.json5
          token: '${{ steps.generate_token.outputs.token }}'
        env:
          LOG_LEVEL: 'debug'
